// <auto-generated />
namespace Jump_Trampoline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeAgregaTablaparaMostrarVideos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeAgregaTablaparaMostrarVideos));
        
        string IMigrationMetadata.Id
        {
            get { return "202209170009512_SeAgregaTablaparaMostrarVideos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
